--liquibase formatted sql
--changeset donald@awesomatic.co.za:salon-service-details.sql

CREATE TABLE salon_service_detail (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255),
    price bigint,
    time_in_minutes integer
);

ALTER TABLE ONLY salon_service_detail ADD CONSTRAINT salon_service_detail_pkey PRIMARY KEY (id);

ALTER TABLE salon_service_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME salon_service_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);